<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/dataTables.bootstrap.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/jszip.min.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/pdfmake.min.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/vfs_fonts.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/plugins/datatables/buttons.html5.min.js"></script>
<script type="text/javascript" src="<?php echo 'http://'.$_SERVER["HTTP_HOST"];?>/asignacionfs/js/myfunctions_js.js"></script>
